In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler, normalize

# Álgebra lineal

## Producto punto entre vectores

El producto punto (o producto escalar) es una operación fundamental en álgebra lineal y se usa en muchos algoritmos de IA, como en redes neuronales y en métodos de optimización.

In [2]:
# Definir dos vectores
x_vector = np.array([1, 2, 3])
y_vector = np.array([4, 5, 6])

# Calcular el producto punto
producto_punto = np.dot(x_vector, y_vector)

print("Producto Punto:", producto_punto)


Producto Punto: 32


## Multiplicación de matrices

La multiplicación de matrices es esencial en IA, especialmente en la propagación hacia adelante y hacia atrás en redes neuronales.

In [3]:
# Definir dos matrices
matriz_a = np.array([[1, 2, 3],
                     [4, 5, 6]])
matriz_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Calcular la multiplicación de matrices
resultado = np.dot(matriz_a, matriz_b)

print("Multiplicación de Matrices:\n", resultado)


Multiplicación de Matrices:
 [[ 58  64]
 [139 154]]


# Vector ortogonal

Dos vectores se consideran ortogonales si su producto punto (producto escalar) es igual a cero. Es decir, los vectores son perpendiculares entre sí en el espacio n-dimensional. En el espacio bidimensional y tridimensional, los vectores ortogonales son aquellos que forman un ángulo de 90 grados.

Propiedad de los Vectores Ortogonales:
Dado dos vectores
$𝑎=(𝑎_1,𝑎_2,…,𝑎_𝑛)$ y $𝑏=(𝑏_1,𝑏_2,…,𝑏_𝑛)$, estos son ortogonales si:

$𝑎⋅𝑏=𝑎_1⋅𝑏_1+𝑎_2⋅𝑏_2+…+𝑎_𝑛⋅𝑏_𝑛=0$


In [4]:
# Definimos dos vectores
a = np.array([1, 2, 3])
b = np.array([4, -2, 0])

# Calculamos el producto punto
dot_product = np.dot(a, b)

# Verificamos si los vectores son ortogonales
print("Los vectores son ortogonales." if dot_product == 0 else "Los vectores no son ortogonales.")
print(f"Producto punto: {dot_product}")


Los vectores son ortogonales.
Producto punto: 0


# Matriz ortogonal

Una matriz es ortogonal si sus columnas (y filas) son vectores ortogonales unitarios, es decir, los vectores son perpendiculares entre sí y tienen una longitud de 1. Matemáticamente, una matriz cuadrada 𝐴 de tamaño 𝑛×𝑛 es ortogonal si cumple con la siguiente condición:

$𝐴^𝑇𝐴$=𝐴$𝐴^𝑇$=𝐼

donde:

$𝐴^𝑇$ es la transpuesta de la matriz 𝐴.
𝐼 es la matriz identidad de tamaño 𝑛×𝑛.

**Propiedades de una Matriz Ortogonal**
+ Vectores Ortogonales y Normalizados: las columnas (o filas) de una matriz ortogonal son vectores ortogonales entre sí (es decir, su producto punto es cero) y son vectores unitarios (es decir, su norma es 1).

+ Preservación de Longitudes y Ángulos: la transformación lineal que representa una matriz ortogonal preserva las longitudes de los vectores y los ángulos entre ellos. Por lo tanto, una matriz ortogonal representa una transformación rígida (como una rotación o reflexión).

+ Inversa Igual a la Transpuesta: Para una matriz ortogonal
𝐴, la inversa de la matriz es igual a su transpuesta: $𝐴^{−1}$=$𝐴^𝑇$

+ Determinante Igual a ±1: el determinante de una matriz ortogonal es siempre +1 o −1. Esto implica que no cambia el volumen de los vectores transformados (lo preserva o lo refleja).

**Ejemplo de una matriz ortogonal**
Una matriz de rotación de 90º en el plano 2D es un ejemplo clásico de matriz ortogonal: *A* =$\begin{equation}
\begin{bmatrix}
0 & -1 \\
1 & 0\\
\end{bmatrix}
\end{equation}$

Para verificar que *A* es ortogonal, se puede comprobar que:

$A^T$=$\begin{equation}
\begin{bmatrix}
0 & 1 \\
-1 & 0\\
\end{bmatrix}
\end{equation}$$\begin{equation}
\begin{bmatrix}
0 & -1 \\
1 & 0\\
\end{bmatrix}
\end{equation}$=$\begin{equation}
\begin{bmatrix}
1 & 0 \\
0 & 1\\
\end{bmatrix}
\end{equation}$

Dado que el resultado es la matriz identidad, entonces *A* es ortogonal!!!.


# Vector propio

Un vector propio (o autovector) de una matriz es un vector no nulo que cambia de magnitud pero no de dirección cuando se aplica la matriz a él. Es decir, si se tiene una matriz
𝐴 y un vector 𝑣, el vector 𝑣 es un vector propio de 𝐴 si cumple con la siguiente ecuación:

𝐴𝑣=𝜆𝑣 donde:

+ 𝐴 es una matriz cuadrada.
+ 𝑣 es el vector propio.
+ 𝜆 es un valor propio (o autovalor), que es un escalar.

El valor propio asociado a un vector propio indica en qué medida se escala el vector propio cuando se aplica la matriz 𝐴.



In [5]:
# Define una matriz cuadrada
A = np.array([[4, 1],
              [2, 3]])

# Calcula los valores propios (autovalores) y los vectores propios (autovectores)
valores_propios, vectores_propios = np.linalg.eig(A)

print("Valores Propios:")
print(valores_propios)

print("\nVectores Propios:")
print(vectores_propios)


Valores Propios:
[5. 2.]

Vectores Propios:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


## Descomposición en valores singulares (SVD)

SVD es una técnica importante en la reducción de dimensionalidad y se utiliza en métodos como PCA y en el tratamiento de datos en IA.


Es una técnica que descompone una matriz en tres matrices:
𝑈,𝑆 y $𝑉^𝑇$. Esta descomposición es muy útil en diversas áreas, como el análisis de datos, la reducción de dimensionalidad, la compresión de imágenes, entre otros.

Funciona de la siguiente manera: para una matriz 𝐴 de dimensión $𝑚×𝑛$ la descomposición en valores singulares se expresa como:

$𝐴=𝑈⋅𝑆⋅𝑉^𝑇$

donde:
+ 𝑈 es una matriz ortogonal de tamaño 𝑚×𝑚. Sus columnas son los vectores propios de $𝐴𝐴^T$
+ 𝑆 es una matriz diagonal de tamaño 𝑚×𝑛, que contiene los valores singulares de 𝐴 ordenados de mayor a menor.
+ $𝑉^𝑇$ es la transpuesta de una matriz ortogonal 𝑉 de tamaño 𝑛×𝑛. Sus columnas son los vectores propios de $𝐴^𝑇𝐴$.

In [15]:
# Crear una matriz
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Aplicar SVD
U, S, Vt = np.linalg.svd(matriz)
print("A:\n", matriz)
print("-"*50)
print("Matriz U:\n", U)
print("-"*50)
print("Valores singulares S:\n", S)
print("-"*50)
print("Matriz V traspuesta:\n", Vt)


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
Matriz U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
--------------------------------------------------
Valores singulares S:
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]
--------------------------------------------------
Matriz V traspuesta:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


1. Matriz 𝑈: esta es una matriz ortogonal que contiene los vectores propios de 𝐴$𝐴^𝑇$. Dado que 𝐴 es una matriz de tamaño
3×3, 𝑈 también será de tamaño 3×3. Cada columna de 𝑈 es un vector propio de 𝐴$𝐴^𝑇$ y está normalizada.

2. Valores singulares 𝑆:𝑆 contiene los valores singulares de la matriz original, que son las raíces cuadradas de los valores propios de $𝐴^𝑇$𝐴. Estos valores están ordenados de mayor a menor. En NumPy, np.linalg.svd devuelve 𝑆 como un vector de valores singulares (no como una matriz diagonal), por lo que el resultado es un vector de tamaño 3 para esta matriz 3x3.

3. Matriz $𝑉^𝑇$: esta es la transpuesta de la matriz ortogonal
𝑉 que contiene los vectores propios de $𝐴^𝑇𝐴$. Dado que
𝐴 es una matriz de tamaño 3×3, $𝑉^𝑇$ también será de tamaño 3×3.

In [16]:
def es_ortogonal(matriz):
    # Calcular la transpuesta de la matriz
    matriz_transpuesta = matriz.T

    # Multiplicar la matriz por su transpuesta
    resultado = np.dot(matriz, matriz_transpuesta)

    # Crear una matriz identidad del mismo tamaño
    identidad = np.eye(matriz.shape[0])

    # Comprobar si el resultado es igual a la matriz identidad
    return np.allclose(resultado, identidad)

In [18]:
# Comprueba si la matriz U es ortogonal
es_ortogonal(U)

True

In [4]:
# Crear una matriz de ejemplo
x_matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(x_matriz[:,0])
print(np.linalg.norm(x_matriz[:,0]))

[1 4 7]
8.12403840463596


## Tensores y escalares

Un tensor es un objeto matemático que generaliza la noción de escalares, vectores y matrices. En términos más simples, un tensor puede ser un número, un vector, una matriz o cualquier colección de estos objetos. En el contexto del aprendizaje profundo y la biblioteca TensorFlow, los tensores se utilizan para representar datos multidimensionales.

**Diferencia con Escalar:**

Escalar: Es simplemente un número, como 15 o -29. Un escalar tiene magnitud pero no dirección. Puede considerarse un tensor de rango 0, ya que no tiene dimensiones.

Tensor: Es un objeto más general que puede contener múltiples escalares organizados en una estructura multidimensional. Por ejemplo, un vector de números es un tensor de rango 1, una matriz es un tensor de rango 2, y así sucesivamente.


In [ ]:
# Escalar (Tensor de rango 0)
escalar = 29

In [ ]:
# Vector (Tensor de rango 1)
vector = np.array([1, 2, 3])
print("Vector\n", vector)

# Matriz (Tensor de rango 2)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz\n", matriz)

# Tensor de rango 3
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("Tensor 3D\n", tensor_3d)

En estos ejemplos, *escalar* es un tensor de rango 0, vector es un tensor de rango 1, *matriz* es un tensor de rango 2, y *tensor_3d* es un tensor de rango 3.
Los tensores son fundamentales en el aprendizaje profundo (Deep Learning), donde representan datos en conjuntos de muestras con múltiples dimensiones.

## Operaciones entre vectores

In [ ]:
# Suma
a = np.array([1, 2, 4])
b = np.array([15,25,30])
c = a + b
print(c)

In [ ]:
# Resta
a = np.array([1, 2, 4])
b = np.array([15,25,30])
c = a - b
print(c)

In [ ]:
# Multiplicación
a = np.array([1, 2, 4])
b = np.array([15,25,30])
c = a * b
print(c)

In [ ]:
# División
a = np.array([1, 2, 4])
b = np.array([15,25,30])
c = a / b
print(c)

In [ ]:
# Usando escalares
a = np.array([15,3,25])
b = a + 7
print(b)

## Funciones universales

In [ ]:
valores = np.array([2,3,5,6])
print("Elementos", valores)

In [ ]:
# Suma de los valores
np.sum(valores)

In [ ]:
# Acumula los valores del arreglo
np.cumsum(valores)

In [ ]:
# Obtiene la productoria de los elementos del arreglo
np.cumprod(valores)

In [ ]:
valores = np.array([[2,4,5,6],[8,10,15,50]])
valores

In [ ]:
# Suma todos lo valores del arreglo bidimensional
np.sum(valores)

In [ ]:
# Suma los valores por fila
np.sum(valores, axis = 1)

In [ ]:
# Suma los valores por columna
np.sum(valores, axis = 0)

## Manipulación de forma

In [ ]:
# Creación de los elementos
elementos = np.array([[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]])
elementos

In [ ]:
# Obtiene la cantidad de filas y columnas
elementos.shape

In [ ]:
# Reorganiza en 4 filas y 3 columnas
elementos.reshape(4,3)

In [ ]:
# Reorganiza en 2 filas y 6 columnas
elementos.reshape(2,6)

In [ ]:
# Obtiene la traspuesta - Alternativa 1
elementos.T

In [ ]:
# Obtiene la traspuesta - Alternativa 2
elementos.transpose()

In [ ]:
# Obtiene los elementos como una lista - Alternativa 1
elementos.ravel()

In [ ]:
# Obtiene los elementos como una lista - Alternativa 2
elementos.flatten()

## Indexación y selección

In [ ]:
valores = np.array([20,3,5,6,1,-3,10,45,43,50,4])
print("Elementos", valores)

In [ ]:
# Acceso a un elemento, por su índice
valores[4]

In [ ]:
# Selección con uso de slice - Versión 1
valores[:2]

In [ ]:
# Selección con uso de slice - Versión 2
valores[4:]

In [ ]:
# Selección con uso de slice - Versión 3
valores[4:10]

In [ ]:
# Selección usando condición
valores[valores > 15]

# Probabilidad

## Distribución normal

Las distribuciones normales son fundamentales en probabilidad y estadísticas y son ampliamente utilizadas en IA, por ejemplo, en técnicas de regresión y modelos probabilísticos.

In [ ]:
# Definir parámetros de la distribución
media = 0
desviacion_estandar = 1

# Generar una distribución normal
x = np.linspace(-5, 5, 100)
y = norm.pdf(x, media, desviacion_estandar)

# Graficar la distribución
plt.plot(x, y)
plt.title("Distribución Normal")
plt.xlabel("Valor")
plt.ylabel("Densidad de probabilidad")
plt.show()


## Teorema de Bayes

El teorema de Bayes se utiliza en métodos de clasificación como el clasificador Naive Bayes y en la inferencia probabilística en redes bayesianas.

In [ ]:
# Probabilidades previas
p_A = 0.4
p_B = 0.6

# Probabilidad condicional
p_B_dado_A = 0.7

# Aplicar el teorema de Bayes
p_A_dado_B = (p_B_dado_A * p_A) / p_B

print("P(A|B) usando el Teorema de Bayes:", p_A_dado_B)
