# Explicación del concepto de kernel

**Autor:** Jazna Meza Hidalgo

**Correo Electrónico:** ymeza@ubiobio.cl

**Fecha de Creación:** Diciembre de 2024  
**Versión:** 1.0  

---

## Descripción

Este notebook contiene la explicación del uso de kernel sobre una imagen que va a contribuir con el entendimiento de la forma en la que se procesan las imágenes en una red neuronal convolucional (CNN)

---

## Requisitos de Software

Este notebook fue desarrollado con Python 3.9. A continuación se listan las bibliotecas necesarias:

- numpy (1.26.4)


In [ ]:
# Descargar el archivo
!wget https://raw.githubusercontent.com/JaznaLaProfe/InteligenciaArtificial/main/data/imagen.jpeg

--2024-12-05 22:37:30--  https://raw.githubusercontent.com/JaznaLaProfe/InteligenciaArtificial/main/data/imagen.jpeg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1748870 (1.7M) [image/jpeg]
Saving to: ‘imagen.jpeg’

imagen.jpeg         100%[===================>]   1.67M  --.-KB/s    in 0.07s   

2024-12-05 22:37:31 (23.7 MB/s) - ‘imagen.jpeg’ saved [1748870/1748870]



In [ ]:
import numpy as np

from PIL import Image, ImageFilter

In [ ]:
imgpath = 'imagen.jpeg'
img = Image.open(imgpath)
img = img.convert('RGB')
display(img)

In [ ]:
imgmatrix = np.asarray(img, dtype=np.uint8)
print (imgmatrix)

[[[173 202 216]
  [173 202 216]
  [173 202 216]
  ...
  [131 177 192]
  [131 177 192]
  [131 177 192]]

 [[173 202 216]
  [173 202 216]
  [173 202 216]
  ...
  [132 178 193]
  [132 178 193]
  [132 178 193]]

 [[173 202 216]
  [173 202 216]
  [173 202 216]
  ...
  [132 178 193]
  [132 178 193]
  [132 178 193]]

 ...

 [[139 154 157]
  [138 153 156]
  [137 152 155]
  ...
  [ 79  97 111]
  [ 78  97 112]
  [ 85 104 118]]

 [[142 161 159]
  [141 160 158]
  [143 162 160]
  ...
  [ 71  93 104]
  [ 65  89 101]
  [ 66  93 102]]

 [[144 165 160]
  [143 164 159]
  [146 167 162]
  ...
  [ 76  98 109]
  [ 69  98 106]
  [ 71 101 109]]]


In [ ]:
imgmatrix.shape

(2002, 3000, 3)

# Kernel 1

In [ ]:
kernelValues = [-1,-1,-1,-1, 8,-1,-1,-1,-1]
np.reshape(kernelValues, (3,3))

array([[-1, -1, -1],
       [-1,  8, -1],
       [-1, -1, -1]])

In [ ]:
kernel = ImageFilter.Kernel((3,3), kernelValues, 1, 0)
imagen_filter = img.filter(kernel)
display(imagen_filter)

**Comentarios**

+ El kernel anterior es un filtro de detección de bordes o de realce de bordes.

+ Es un filtro de tamaño 3×3, lo que significa que operará en vecindarios de 3x3 píxeles de la imagen.

+ El centro del kernel tiene un valor 8, y los demás elementos tienen valores -1.

**Operación matemática**

+ Para cada píxel de la imagen, multiplicar los valores de intensidad del vecindario (los píxeles vecinos) por los valores correspondientes en el kernel.
+ Sumar todos esos productos.
+ Dividir por la normalización (en este caso, es 1, así que no hay cambio).
+ Agregar el sesgo (en este caso, es 0, por lo que no se agrega nada extra).

**Función del kernel**

+ Este kernel destaca la diferencia de intensidad entre un píxel y sus vecinos.
+ Si un píxel tiene una intensidad muy diferente a la de sus vecinos, el resultado será un valor alto (realzando el borde en esa región).
+ Si el píxel tiene una intensidad similar a sus vecinos, el resultado será cercano a 0 (suprimiendo las áreas uniformes).

**Resultado**
+ Obtendrás una imagen resaltando los bordes y los cambios abruptos de intensidad en la imagen original.
+ Las áreas homogéneas (sin cambios en la intensidad) serán casi negras, mientras que los bordes y los detalles tendrán valores altos (brillantes).
+ Este filtro es útil para detección de bordes y realce de detalles en imágene

# Kernel 2

In [ ]:
x_kernelValues = [1,-2, -1, 0,0,0,1,1,2]
np.reshape(x_kernelValues, (3,3))


array([[ 1, -2, -1],
       [ 0,  0,  0],
       [ 1,  1,  2]])

In [ ]:
kernel = ImageFilter.Kernel((3,3), x_kernelValues, 1, 0)
imagen_filter = img.filter(kernel)
display(imagen_filter)

**Función del Kernel**

Este kernel realiza un tipo de detección de bordes direccionada, específicamente para resaltar los cambios en la intensidad de los píxeles a lo largo de una dirección. En este caso:

+ Los valores positivos (en la parte inferior derecha del kernel) y los valores negativos (en la parte superior izquierda) sugieren que este filtro realza los cambios de intensidad a lo largo de una dirección diagonal, de arriba-izquierda a abajo-derecha.

+ Los valores centrales son ceros, lo que significa que no se considera la intensidad del píxel central directamente.

**Operación Matemática**

El proceso consiste en:

+ Multiplicar los valores del vecindario 3×3 de cada píxel por los valores correspondientes del kernel.

+ Sumar los productos, generando una nueva intensidad para el píxel procesado.
**Características del Kernel**
Diferencias diagonales:
+ Detecta bordes diagonales, principalmente los que están alineados desde arriba a la izquierda hacia abajo a la derecha.

Refuerzo direccional:
+ Las diferencias de intensidad en esa dirección serán amplificadas.
+ En cambio, bordes o cambios en direcciones no alineadas con el kernel (por ejemplo, vertical u horizontal) no serán tan destacados.

**Resultado**
+ Los bordes diagonales que van de arriba-izquierda hacia abajo-derecha serán más prominentes.
+ Las regiones con cambios en intensidad en otras direcciones tendrán menor importancia o estarán atenuadas.

**Aplicaciones**

Este tipo de filtro es útil en:

+ Detección de bordes direccionales en imágenes.
+ Análisis de texturas o características con orientaciones específicas.
+ Tareas como preprocesamiento en visión por computadora para resaltar detalles clave en la dirección del kernel.

# Kernel 3

In [ ]:
x_kernelValues = [-1,0, 1, -2,0,2, -1,0,1]
np.reshape(x_kernelValues, (3,3))

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [ ]:
kernel = ImageFilter.Kernel((3,3), x_kernelValues, 1, 0)

imagen_filter = img.filter(kernel)

display(imagen_filter)

**Función del Kernel**

Este kernel es un filtro Sobel en dirección horizontal (también conocido como Sobel-X), ampliamente utilizado en el procesamiento de imágenes para detectar bordes horizontales. En este caso, está diseñado para resaltar cambios de intensidad de izquierda a derecha en la imagen.

**Características principales:**

Los valores en la izquierda son negativos , en el centro son ceros y en la derecha son positivos.
Esto mide cómo cambia la intensidad de los píxeles de izquierda a derecha en cada vecindario 3×3.

**Operación del Kernel**

**Aplicación**:

+ Para cada píxel, se toma su vecindario 3×3.
+ Se multiplican los valores del vecindario por los valores correspondientes del kernel.
+ Se suman los productos para calcular el nuevo valor de intensidad para ese píxel.

El resultado es un mapa de bordes horizontales en la imagen:

+ Los bordes donde los valores cambian de bajo a alto de izquierda a derecha tendrán valores positivos.
+ Los bordes donde los valores cambian de alto a bajo de izquierda a derecha tendrán valores negativos.
+ Las regiones homogéneas tendrán un valor cercano a cero (se atenúan).

**Resultado del Filtro**
Este kernel produce:

+ Detección de bordes horizontales: cambios abruptos de intensidad en la dirección horizontal (izquierda-derecha).
+ Contraste direccional: resalta líneas y contornos que separan áreas claras y oscuras a lo largo de la dirección horizontal.

**Comparación con el Kernel Sobel Vertical**
El kernel Sobel vertical (o Sobel-Y) es similar, pero orientado a cambios verticales. Tiene la forma:

 [-1, -2, -1,
                   0,  0,  0,
                   1,  2,  1]

Usando ambos (Sobel-X y Sobel-Y), es posible calcular el gradiente de intensidad completo de la imagen y combinar los resultados para una detección general de bordes.

**Aplicaciones**
+ Detección de bordes horizontales en visión por computadora.
+ Segmentación de imágenes.
+ Análisis de texturas y contornos en imágenes.

Este kernel es parte de los filtros Sobel, que son rápidos y efectivos para tareas de procesamiento de imágenes.

# Kernel 4

In [ ]:
z_kernelValues = [-1, -1, -1, 2,  2,  2, -1, -1, -1]
np.reshape(z_kernelValues, (3,3))

array([[-1, -1, -1],
       [ 2,  2,  2],
       [-1, -1, -1]])

In [ ]:
kernel = ImageFilter.Kernel((3,3), z_kernelValues, 1, 0)

imagen_filter = img.filter(kernel)

display(imagen_filter)